# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

---

- name: fstrim cron job
  copy:
    src: fstrim.cron.sh
    dest: /etc/periodic/daily/fstrim
    owner: root
    group: root
    mode: 0755
