# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright 2023 MNX Cloud, Inc.

---

- name: enable cloud-init
  shell: setup-cloud-init

- name: fstrim cron job
  copy:
    src: fstrim.cron.sh
    dest: /etc/periodic/daily/fstrim
    owner: root
    group: root
    mode: 0755


- name: Triton sdcvmtools mdata-client
  copy:
    src: "{{ item }}"
    dest: /usr/sbin/
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - "alpine-3/usr/sbin/mdata-*"

- name: Disable getty on ttyS1-3
  copy:
    src: alpine-3/etc/inittab 
    dest: /etc/ 
    owner: root
    group: root
    mode: 0755
